<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="assignment" nsURI="platform:/plugin/assignment1/model/assignment.ecore"
    nsPrefix="assignment">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/acceleo/query/1.0 http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="CourseNeedsACode creditsNeedsToBePositive"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="creditsNeedsToBePositive" value="self.credits>0.0f"/>
      <details key="CourseNeedsACode" value="self.code->notEmpty()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="studylevel" eType="#//Studylevel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="7.5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Department">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ProgramNeedsToBeUnique CourseNeedsToBeUnique"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="course" upperBound="-1"
        eType="#//Course" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programs" upperBound="-1"
        eType="#//Program" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Program">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ProgramStartyearAndEndyearMustBeValid LengthOfProgramInYearsMustBePositive"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="ProgramStartyearAndEndyearMustBeValid" value="self.endyear > self.startyear or self.endyear = 0"/>
      <details key="LengthOfProgramInYearsMustBePositive" value="self.lengthOfProgramInyears>0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialisation" upperBound="-1"
        eType="#//Specialisation" containment="true" eOpposite="#//Specialisation/program"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lengthOfProgramInyears"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semseters" upperBound="-1"
        eType="#//Semester" containment="true" eOpposite="#//Semester/program"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startyear" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endyear" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Semester">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SemesterStartyearAndEndyearMustBeValid NumberOfCreditsInASemesterMustBeValid"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="SemesterStartyearAndEndyearMustBeValid" value="self.endyear > self.startyear or self.endyear = 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="semesternr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectableCourse" upperBound="-1"
        eType="#//Course"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mandatoryCourse" upperBound="-1"
        eType="#//Course"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialisation" eType="#//Specialisation"
        eOpposite="#//Specialisation/semester"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startyear" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endyear" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="program" lowerBound="1"
        eType="#//Program" eOpposite="#//Program/semseters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specialisation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SpesialisationStartyearAndEndyearMustBeValid"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="SpesialisationStartyearAndEndyearMustBeValid" value="self.endyear > self.startyear or self.endyear = 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="program" lowerBound="1"
        eType="#//Program" eOpposite="#//Program/specialisation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semester" upperBound="-1"
        eType="#//Semester" eOpposite="#//Semester/specialisation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startyear" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endyear" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Studylevel">
    <eLiterals name="firstlevel" literal="1stlevel"/>
    <eLiterals name="secondlevel" value="1" literal="2stlevel"/>
    <eLiterals name="thirdstlevel" value="2" literal="3stlevel"/>
    <eLiterals name="higherlevel" value="3" literal="higher level"/>
  </eClassifiers>
</ecore:EPackage>
